<?php
defined( 'ABSPATH' ) || exit;

final class SLC_Admin {
	public function hooks() { add_action( 'admin_menu', array( $this, 'menu' ) ); add_action( 'admin_post_slc_review_lesson', array( $this, 'review' ) ); add_action( 'admin_notices', array( $this, 'notice' ) ); }
	public function menu() { add_menu_page( 'Learning Management', 'Learning Management', 'manage_sabri_learning', 'sabri-learning', array( $this, 'dashboard' ), 'dashicons-welcome-learn-more', 29 ); add_submenu_page( 'sabri-learning', 'Lesson Moderation', 'Lesson Moderation', 'manage_sabri_learning', 'sabri-learning', array( $this, 'dashboard' ) ); add_submenu_page( 'sabri-learning', 'Learning Books', 'Books', 'manage_sabri_learning', 'edit.php?post_type=' . SLC_Content::BOOK ); add_submenu_page( 'sabri-learning', 'All Lessons', 'All Lessons', 'manage_sabri_learning', 'edit.php?post_type=' . SLC_Content::LESSON ); add_submenu_page( 'sabri-learning', 'Comments', 'Comments', 'manage_sabri_learning', 'edit-comments.php' ); }
	public function dashboard() { $this->guard(); $status = isset( $_GET['lesson_status'] ) ? sanitize_key( wp_unslash( $_GET['lesson_status'] ) ) : 'pending'; if ( ! in_array( $status, array( 'pending', 'publish', 'draft', 'private' ), true ) ) { $status = 'pending'; } $lessons = get_posts( array( 'post_type' => SLC_Content::LESSON, 'post_status' => $status, 'posts_per_page' => 100, 'orderby' => 'date', 'order' => 'DESC' ) ); ?>
		<div class="wrap slc-admin"><h1>Learning Management</h1><p>Review educational accuracy, references, American English, copyright, patient privacy and medical safety before publication.</p><nav><?php foreach ( array( 'pending' => 'Pending', 'publish' => 'Published', 'draft' => 'Rejected / Draft', 'private' => 'Hidden' ) as $key => $label ) : ?><a class="<?php echo $status === $key ? 'is-active' : ''; ?>" href="<?php echo esc_url( add_query_arg( array( 'page' => 'sabri-learning', 'lesson_status' => $key ), admin_url( 'admin.php' ) ) ); ?>"><?php echo esc_html( $label ); ?></a><?php endforeach; ?></nav><table class="widefat striped"><thead><tr><th>Lesson</th><th>Classification</th><th>Author</th><th>Review</th></tr></thead><tbody><?php if ( $lessons ) : foreach ( $lessons as $lesson ) : ?><tr><td><strong><?php echo esc_html( $lesson->post_title ); ?></strong><p><?php echo esc_html( $lesson->post_excerpt ); ?></p><details><summary>Review full lesson</summary><div class="slc-admin-content"><?php echo wp_kses_post( wpautop( $lesson->post_content ) ); ?><h4>References</h4><?php echo nl2br( esc_html( get_post_meta( $lesson->ID, '_slc_references', true ) ) ); ?></div></details></td><td><?php echo esc_html( SLC_Content::term( $lesson->ID, SLC_Content::TOPIC ) ); ?><br><?php echo esc_html( SLC_Content::term( $lesson->ID, SLC_Content::LEVEL ) ); ?><?php if ( 'patient-case-learning' === SLC_Content::term( $lesson->ID, SLC_Content::TOPIC, 'slug' ) ) : ?><br><strong>Patient safeguards: <?php echo '1' === get_post_meta( $lesson->ID, '_slc_case_anonymized', true ) && '1' === get_post_meta( $lesson->ID, '_slc_case_consent', true ) ? 'Confirmed' : 'Missing'; ?></strong><?php endif; ?></td><td><?php echo esc_html( get_the_author_meta( 'display_name', $lesson->post_author ) ); ?><br><?php echo esc_html( SLC_Permissions::label( $lesson->post_author ) ); ?></td><td><?php echo $this->form( $lesson ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></td></tr><?php endforeach; else : ?><tr><td colspan="4">No lessons in this view.</td></tr><?php endif; ?></tbody></table></div><?php }
	private function form( $lesson ) { ob_start(); ?><form class="slc-review" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" method="post"><input type="hidden" name="action" value="slc_review_lesson"><input type="hidden" name="lesson_id" value="<?php echo absint( $lesson->ID ); ?>"><?php wp_nonce_field( 'slc_review_' . $lesson->ID ); ?><select name="review_action"><option value="approve">Approve and publish</option><option value="reject">Reject to draft</option><option value="hide">Hide lesson</option></select><textarea name="note" rows="3" placeholder="Internal review note"></textarea><button class="button button-primary" type="submit">Apply</button></form><?php return ob_get_clean(); }
	public function review() { $this->guard(); $id = isset( $_POST['lesson_id'] ) ? absint( $_POST['lesson_id'] ) : 0; check_admin_referer( 'slc_review_' . $id ); $lesson = get_post( $id ); $action = isset( $_POST['review_action'] ) ? sanitize_key( wp_unslash( $_POST['review_action'] ) ) : ''; $note = isset( $_POST['note'] ) ? sanitize_textarea_field( wp_unslash( $_POST['note'] ) ) : ''; if ( ! $lesson || SLC_Content::LESSON !== $lesson->post_type || ! in_array( $action, array( 'approve', 'reject', 'hide' ), true ) ) { wp_die( esc_html__( 'Invalid review request.', 'sabri-learning' ), '', array( 'response' => 400 ) ); } if ( 'approve' === $action ) { $topic = SLC_Content::term( $id, SLC_Content::TOPIC, 'slug' ); $level = SLC_Content::term( $id, SLC_Content::LEVEL, 'slug' ); if ( ! SLC_Content::allowed( $topic, SLC_Content::TOPIC ) || ! SLC_Content::allowed( $level, SLC_Content::LEVEL ) || ( 'patient-case-learning' === $topic && ( '1' !== get_post_meta( $id, '_slc_case_anonymized', true ) || '1' !== get_post_meta( $id, '_slc_case_consent', true ) ) ) ) { wp_die( esc_html__( 'Topic, level or Patient Case safeguards are incomplete.', 'sabri-learning' ), '', array( 'response' => 400 ) ); } if ( ! SLC_Permissions::is_founder( $lesson->post_author ) && ! user_can( $lesson->post_author, 'manage_sabri_learning' ) && ! SLC_Permissions::is_verified_doctor( $lesson->post_author ) ) { wp_die( esc_html__( 'The author is no longer approved.', 'sabri-learning' ), '', array( 'response' => 400 ) ); } wp_update_post( array( 'ID' => $id, 'post_status' => 'publish' ) ); } elseif ( 'reject' === $action ) { wp_update_post( array( 'ID' => $id, 'post_status' => 'draft' ) ); update_post_meta( $id, '_slc_review_note', $note ); } else { wp_update_post( array( 'ID' => $id, 'post_status' => 'private' ) ); } self::audit( $id, $action, $note ); wp_safe_redirect( admin_url( 'admin.php?page=sabri-learning' ) ); exit; }
	public static function audit( $lesson, $action, $note ) { global $wpdb; $wpdb->insert( $wpdb->prefix . 'slc_audit_log', array( 'lesson_id' => absint( $lesson ), 'actor_id' => get_current_user_id(), 'action' => sanitize_key( $action ), 'note' => sanitize_textarea_field( $note ), 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s', '%s', '%s' ) ); }
	private function guard() { if ( ! current_user_can( 'manage_sabri_learning' ) ) { wp_die( esc_html__( 'You cannot manage learning content.', 'sabri-learning' ), '', array( 'response' => 403 ) ); } }
	public function notice() { if ( current_user_can( 'manage_sabri_learning' ) && get_transient( 'slc_activation_notice' ) ) { delete_transient( 'slc_activation_notice' ); echo '<div class="notice notice-success is-dismissible"><p><strong>Learn Sabri Classical Homeopathy is active.</strong> Review the public learning page and Learning Management dashboard.</p></div>'; } }
}

