<?php
defined( 'ABSPATH' ) || exit;

final class SLC_Catalog {
	public function hooks() { add_shortcode( 'slc_learning_home', array( $this, 'home' ) ); add_filter( 'the_content', array( $this, 'replace_foundation' ), 8 ); add_filter( 'the_content', array( $this, 'lesson_author' ), 19 ); add_filter( 'the_content', array( $this, 'single_content' ), 20 ); add_filter( 'the_content', array( $this, 'lesson_navigation' ), 21 ); add_action( 'template_redirect', array( $this, 'guard' ), 1 ); }
	public function replace_foundation( $content ) { if ( ! is_singular( 'page' ) || ! in_the_loop() || ! is_main_query() ) { return $content; } $pages = (array) get_option( 'spf_page_map', array() ); if ( ! empty( $pages['learn'] ) && (int) $pages['learn'] === (int) get_queried_object_id() && has_shortcode( $content, 'sabri_platform_module' ) ) { return '[slc_learning_home]'; } return $content; }
	public function home() { $books = get_posts( array( 'post_type' => SLC_Content::BOOK, 'post_status' => 'publish', 'posts_per_page' => 12, 'orderby' => 'menu_order title', 'order' => 'ASC' ) ); ob_start(); ?>
		<main class="slc-shell"><div class="slc-main-nav"><?php echo $this->navigation( 'learn' ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div><header class="slc-hero"><div><span>Learn Sabri Classical Homeopathy</span><h1>Books, Lessons and Responsible Classical Study</h1><p>Read public learning material freely. Log in to bookmark lessons, record progress and take knowledge checks.</p></div><form method="get" role="search"><label class="screen-reader-text" for="slc-search">Search lessons</label><input id="slc-search" name="lesson_search" type="search" placeholder="Search books and lessons"><button type="submit">Search</button></form></header>
		<section><div class="slc-section-head"><div><span>Structured Path</span><h2>Choose Your Learning Level</h2></div><?php $pages = (array) get_option( 'slc_page_map', array() ); if ( is_user_logged_in() && ! empty( $pages['progress'] ) ) : ?><a class="slc-button slc-button-light" href="<?php echo esc_url( get_permalink( $pages['progress'] ) ); ?>">My Learning</a><?php endif; ?></div><div class="slc-levels"><?php foreach ( SLC_Content::levels() as $slug => $name ) : ?><a href="<?php echo esc_url( add_query_arg( 'lesson_level', $slug ) ); ?>"><strong><?php echo esc_html( $name ); ?></strong><span><?php echo 'beginner' === $slug ? 'Start with essential principles and historical foundations.' : ( 'intermediate' === $slug ? 'Build structured case and remedy study.' : ( 'advanced' === $slug ? 'Develop deeper analytical understanding.' : 'Use focused material as a professional study reference.' ) ); ?></span></a><?php endforeach; ?></div></section>
		<section><div class="slc-section-head"><div><span>Founder Publications</span><h2>Learning Book Shelf</h2></div></div><div class="slc-book-grid"><?php foreach ( $books as $book ) : ?><article class="slc-book"><a class="slc-book-cover" href="<?php echo esc_url( get_permalink( $book ) ); ?>" aria-label="Read about <?php echo esc_attr( $book->post_title ); ?>"><span>SH</span></a><div><h3><a href="<?php echo esc_url( get_permalink( $book ) ); ?>"><?php echo esc_html( $book->post_title ); ?></a></h3><p><?php echo esc_html( $book->post_excerpt ); ?></p><a href="<?php echo esc_url( get_permalink( $book ) ); ?>">Read Online</a></div></article><?php endforeach; ?></div></section>
		<section class="slc-master"><div><span>Classical Masters</span><h2>Samuel Hahnemann</h2><p>A responsible historical foundation for understanding the origins of classical homeopathy and its primary literature.</p></div><?php $master = get_page_by_title( 'Samuel Hahnemann and the Foundation of Classical Homeopathy', OBJECT, SLC_Content::LESSON ); if ( $master ) : ?><a class="slc-button" href="<?php echo esc_url( get_permalink( $master ) ); ?>">Open Introductory Lesson</a><?php endif; ?></section>
		<?php echo $this->lessons(); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></main>
		<?php return ob_get_clean(); }

	private function lessons() { $search = isset( $_GET['lesson_search'] ) ? sanitize_text_field( wp_unslash( $_GET['lesson_search'] ) ) : ''; $topic = isset( $_GET['lesson_topic'] ) ? sanitize_title( wp_unslash( $_GET['lesson_topic'] ) ) : ''; $level = isset( $_GET['lesson_level'] ) ? sanitize_title( wp_unslash( $_GET['lesson_level'] ) ) : ''; $book = isset( $_GET['lesson_book'] ) ? absint( $_GET['lesson_book'] ) : 0; $sort = isset( $_GET['lesson_sort'] ) ? sanitize_key( wp_unslash( $_GET['lesson_sort'] ) ) : 'latest'; $tax = array( 'relation' => 'AND', array( 'taxonomy' => SLC_Content::TOPIC, 'field' => 'slug', 'terms' => $topic && SLC_Content::allowed( $topic, SLC_Content::TOPIC ) ? array( $topic ) : array_keys( SLC_Content::topics() ) ), array( 'taxonomy' => SLC_Content::LEVEL, 'field' => 'slug', 'terms' => $level && SLC_Content::allowed( $level, SLC_Content::LEVEL ) ? array( $level ) : array_keys( SLC_Content::levels() ) ) ); $args = array( 'post_type' => SLC_Content::LESSON, 'post_status' => 'publish', 'posts_per_page' => 12, 's' => $search, 'tax_query' => $tax, 'orderby' => 'date', 'order' => 'DESC' ); if ( $book ) { $args['meta_query'] = array( array( 'key' => '_slc_book_id', 'value' => $book, 'type' => 'NUMERIC' ) ); } if ( 'popular' === $sort ) { $args['meta_key'] = '_slc_views'; $args['orderby'] = 'meta_value_num'; } $q = new WP_Query( $args ); $books = get_posts( array( 'post_type' => SLC_Content::BOOK, 'post_status' => 'publish', 'posts_per_page' => 100, 'orderby' => 'title', 'order' => 'ASC' ) ); ob_start(); ?>
		<section class="slc-lessons" id="learning-lessons"><div class="slc-section-head"><div><span>Public Learning</span><h2>Lessons</h2></div><?php $pages = (array) get_option( 'slc_page_map', array() ); if ( SLC_Permissions::can_submit() && ! empty( $pages['submit'] ) ) : ?><a class="slc-button" href="<?php echo esc_url( get_permalink( $pages['submit'] ) ); ?>">Submit Lesson</a><?php endif; ?></div>
		<form class="slc-filters" method="get"><label>Search<input type="search" name="lesson_search" value="<?php echo esc_attr( $search ); ?>"></label><label>Topic<select name="lesson_topic"><option value="">All topics</option><?php foreach ( SLC_Content::topics() as $slug => $name ) : ?><option value="<?php echo esc_attr( $slug ); ?>" <?php selected( $topic, $slug ); ?>><?php echo esc_html( $name ); ?></option><?php endforeach; ?></select></label><label>Level<select name="lesson_level"><option value="">All levels</option><?php foreach ( SLC_Content::levels() as $slug => $name ) : ?><option value="<?php echo esc_attr( $slug ); ?>" <?php selected( $level, $slug ); ?>><?php echo esc_html( $name ); ?></option><?php endforeach; ?></select></label><label>Book<select name="lesson_book"><option value="0">All books</option><?php foreach ( $books as $item ) : ?><option value="<?php echo absint( $item->ID ); ?>" <?php selected( $book, $item->ID ); ?>><?php echo esc_html( $item->post_title ); ?></option><?php endforeach; ?></select></label><label>Order<select name="lesson_sort"><option value="latest" <?php selected( $sort, 'latest' ); ?>>Latest</option><option value="popular" <?php selected( $sort, 'popular' ); ?>>Popular</option></select></label><button class="slc-button" type="submit">Apply</button></form><div class="slc-lesson-grid"><?php if ( $q->have_posts() ) : while ( $q->have_posts() ) : $q->the_post(); echo $this->card( get_post() ); endwhile; else : ?><div class="slc-empty"><h3>No lessons found</h3><p>Try another topic, level or search phrase.</p></div><?php endif; ?></div></section>
		<?php wp_reset_postdata(); return ob_get_clean(); }

	private function card( $post ) { $id = $post->ID; ob_start(); ?><article class="slc-lesson-card" data-lesson-id="<?php echo absint( $id ); ?>"><?php if ( has_post_thumbnail( $id ) ) : ?><a class="slc-lesson-image" href="<?php echo esc_url( get_permalink( $id ) ); ?>"><?php echo get_the_post_thumbnail( $id, 'medium_large', array( 'loading' => 'lazy', 'alt' => $post->post_title ) ); ?></a><?php endif; ?><div><div class="slc-chips"><span><?php echo esc_html( SLC_Content::term( $id, SLC_Content::TOPIC ) ); ?></span><span><?php echo esc_html( SLC_Content::term( $id, SLC_Content::LEVEL ) ); ?></span></div><h3><a href="<?php echo esc_url( get_permalink( $id ) ); ?>"><?php echo esc_html( $post->post_title ); ?></a></h3><p><?php echo esc_html( wp_trim_words( $post->post_excerpt, 25 ) ); ?></p><small><?php echo esc_html( SLC_Permissions::label( $post->post_author ) ); ?> · <?php echo absint( get_post_meta( $id, '_slc_views', true ) ); ?> views</small><?php echo SLC_Learning::actions( $id ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></div></article><?php return ob_get_clean(); }

	public function single_content( $content ) { if ( ! in_the_loop() || ! is_main_query() ) { return $content; } $id = get_the_ID(); if ( is_singular( SLC_Content::LESSON ) ) { $objectives = get_post_meta( $id, '_slc_objectives', true ); $terms = get_post_meta( $id, '_slc_terms', true ); $refs = get_post_meta( $id, '_slc_references', true ); $book = absint( get_post_meta( $id, '_slc_book_id', true ) ); $chapter = get_post_meta( $id, '_slc_chapter', true ); $time = get_post_meta( $id, '_slc_study_time', true ); $head = '<div class="slc-single-meta"><span>' . esc_html( SLC_Content::term( $id, SLC_Content::TOPIC ) ) . '</span><span>' . esc_html( SLC_Content::term( $id, SLC_Content::LEVEL ) ) . '</span>' . ( $time ? '<span>' . esc_html( $time ) . '</span>' : '' ) . '</div>'; $tail = $objectives ? '<section class="slc-panel"><h2>Learning Objectives</h2>' . $this->lines( $objectives ) . '</section>' : ''; $tail .= $chapter ? '<p><strong>Chapter:</strong> ' . esc_html( $chapter ) . '</p>' : ''; $tail .= $book ? '<p><strong>Related Book:</strong> <a href="' . esc_url( get_permalink( $book ) ) . '">' . esc_html( get_the_title( $book ) ) . '</a></p>' : ''; $tail .= $terms ? '<section class="slc-panel"><h2>Important Terms</h2><p>' . esc_html( $terms ) . '</p></section>' : ''; $tail .= $refs ? '<section class="slc-panel"><h2>References</h2>' . $this->lines( $refs ) . '</section>' : ''; $tail .= SLC_Learning::quiz_form( $id ) . '<p class="slc-disclaimer">This lesson is educational. It does not diagnose, prescribe, promise a cure or replace emergency and qualified medical care.</p>' . SLC_Learning::actions( $id ); return '<article class="slc-single" data-lesson-id="' . absint( $id ) . '">' . $head . $content . $tail . '</article>'; }
		if ( is_singular( SLC_Content::BOOK ) ) { $q = new WP_Query( array( 'post_type' => SLC_Content::LESSON, 'post_status' => 'publish', 'posts_per_page' => 50, 'meta_query' => array( array( 'key' => '_slc_book_id', 'value' => $id, 'type' => 'NUMERIC' ) ), 'orderby' => 'date', 'order' => 'ASC' ) ); $tail = '<section class="slc-panel"><h2>Available Chapters and Lessons</h2>'; if ( $q->have_posts() ) { $tail .= '<ul class="slc-lesson-list">'; while ( $q->have_posts() ) { $q->the_post(); $tail .= '<li><a href="' . esc_url( get_permalink() ) . '">' . esc_html( get_the_title() ) . '</a></li>'; } $tail .= '</ul>'; } else { $tail .= '<p>The organized chapter catalog is ready; authorized lessons will appear here as they are published.</p>'; } wp_reset_postdata(); return '<article class="slc-single slc-book-single">' . $content . $tail . '</section><p class="slc-disclaimer">Read-online access is educational. Paid PDF download and sales are not included in this file.</p></article>'; } return $content; }
	private function lines( $text ) { $out = '<ul>'; foreach ( preg_split( '/\r\n|\r|\n/', $text ) as $line ) { if ( trim( $line ) ) { $out .= '<li>' . esc_html( trim( $line ) ) . '</li>'; } } return $out . '</ul>'; }
	public function lesson_author( $content ) { if ( ! is_singular( SLC_Content::LESSON ) || ! in_the_loop() || ! is_main_query() ) { return $content; } $id = get_the_ID(); $author = absint( get_post_field( 'post_author', $id ) ); return '<div class="slc-author"><strong><a href="' . esc_url( SLC_Permissions::profile_url( $author ) ) . '">' . esc_html( get_the_author_meta( 'display_name', $author ) ) . '</a></strong><span>' . esc_html( SLC_Permissions::label( $author ) ) . ' · Updated ' . esc_html( get_the_modified_date( '', $id ) ) . '</span></div>' . $content; }
	public function lesson_navigation( $content ) { if ( ! is_singular( SLC_Content::LESSON ) || ! in_the_loop() || ! is_main_query() ) { return $content; } $previous = get_previous_post(); $next = get_next_post(); if ( ! $previous && ! $next ) { return $content; } $nav = '<nav class="slc-lesson-nav" aria-label="Lesson navigation">'; $nav .= $previous ? '<a href="' . esc_url( get_permalink( $previous ) ) . '">← Previous Lesson<br><strong>' . esc_html( get_the_title( $previous ) ) . '</strong></a>' : '<span></span>'; $nav .= $next ? '<a href="' . esc_url( get_permalink( $next ) ) . '">Next Lesson →<br><strong>' . esc_html( get_the_title( $next ) ) . '</strong></a>' : '<span></span>'; return $content . $nav . '</nav>'; }
	public function guard() { if ( is_singular( SLC_Content::LESSON ) ) { $id = get_queried_object_id(); if ( ! SLC_Content::allowed( SLC_Content::term( $id, SLC_Content::TOPIC, 'slug' ), SLC_Content::TOPIC ) || ! SLC_Content::allowed( SLC_Content::term( $id, SLC_Content::LEVEL, 'slug' ), SLC_Content::LEVEL ) ) { global $wp_query; $wp_query->set_404(); status_header( 404 ); nocache_headers(); include get_404_template(); exit; } } }
	private function navigation( $active ) { $specs = array( 'home' => array( 'Home', 'sabri-platform-home' ), 'news' => array( 'News', 'sabri-news' ), 'founder' => array( 'Founder', 'sabri-founder' ), 'learn' => array( 'Learn Sabri Classical Homeopathy', 'learn-sabri-classical-homeopathy' ), 'encyclopedia' => array( 'Encyclopedia', 'homeopathy-encyclopedia' ), 'doctors' => array( 'Doctors', 'homeopathy-doctors' ), 'clinic' => array( 'Worldwide Clinic', 'worldwide-clinic' ), 'videos' => array( 'Video Wall', 'video-wall' ), 'reels' => array( 'Reels', 'reels' ), 'pdf' => array( 'PDF Library', 'pdf-library' ), 'radar' => array( 'Radar', 'homeopathy-radar' ), 'ai' => array( 'Sabri Classical Homeopathy AI', 'sabri-classical-homeopathy-ai' ), 'network' => array( 'Network', 'homeopathy-network' ), 'marketplace' => array( 'Marketplace', 'homeopathy-marketplace' ) ); $pages = (array) get_option( 'spf_page_map', array() ); $out = '<nav aria-label="Main platform navigation">'; foreach ( $specs as $key => $spec ) { $url = ! empty( $pages[ $key ] ) ? get_permalink( $pages[ $key ] ) : home_url( '/' . $spec[1] . '/' ); $out .= '<a class="' . ( $active === $key ? 'is-active' : '' ) . '" href="' . esc_url( $url ) . '">' . esc_html( $spec[0] ) . '</a>'; } return $out . '</nav>'; }
}
