<?php
defined( 'ABSPATH' ) || exit;

final class SLC_Learning {
	public function hooks() { add_action( 'wp_ajax_slc_learning_action', array( $this, 'ajax' ) ); add_action( 'template_redirect', array( $this, 'track' ) ); add_shortcode( 'slc_my_learning', array( $this, 'dashboard' ) ); add_filter( 'the_content', array( $this, 'append_level_progress' ), 20 ); }
	public function ajax() {
		check_ajax_referer( 'slc_learning', 'nonce' ); if ( ! is_user_logged_in() ) { wp_send_json_error( array( 'message' => 'Please log in to use learning tools.' ), 401 ); }
		$user = get_current_user_id(); $lesson = isset( $_POST['lessonId'] ) ? absint( $_POST['lessonId'] ) : 0; $kind = isset( $_POST['kind'] ) ? sanitize_key( wp_unslash( $_POST['kind'] ) ) : ''; if ( SLC_Content::LESSON !== get_post_type( $lesson ) || 'publish' !== get_post_status( $lesson ) ) { wp_send_json_error( array( 'message' => 'Lesson not found.' ), 404 ); }
		$key = 'slc_action_' . $user; $count = absint( get_transient( $key ) ); if ( $count > 40 ) { wp_send_json_error( array( 'message' => 'Please wait before trying again.' ), 429 ); } set_transient( $key, $count + 1, MINUTE_IN_SECONDS );
		if ( 'bookmark' === $kind ) { $active = $this->toggle_bookmark( $user, $lesson ); wp_send_json_success( array( 'active' => $active, 'label' => $active ? 'Bookmarked' : 'Bookmark' ) ); }
		if ( 'complete' === $kind ) { $this->progress( $user, $lesson, 'completed' ); wp_send_json_success( array( 'active' => true, 'label' => 'Completed' ) ); }
		if ( 'quiz' === $kind ) { $this->quiz( $user, $lesson ); }
		wp_send_json_error( array( 'message' => 'Unknown learning action.' ), 400 );
	}
	private function toggle_bookmark( $user, $lesson ) { global $wpdb; $table = $wpdb->prefix . 'slc_bookmarks'; $id = $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$table} WHERE user_id=%d AND lesson_id=%d", $user, $lesson ) ); if ( $id ) { $wpdb->delete( $table, array( 'id' => absint( $id ) ), array( '%d' ) ); return false; } $wpdb->insert( $table, array( 'user_id' => $user, 'lesson_id' => $lesson, 'created_at' => current_time( 'mysql', true ) ), array( '%d', '%d', '%s' ) ); return true; }
	private function quiz( $user, $lesson ) { $quiz = get_post_meta( $lesson, '_slc_quiz', true ); if ( ! is_array( $quiz ) || ! $quiz ) { wp_send_json_error( array( 'message' => 'No knowledge check is available.' ), 400 ); } $answers = isset( $_POST['answers'] ) ? json_decode( wp_unslash( $_POST['answers'] ), true ) : array(); if ( ! is_array( $answers ) ) { $answers = array(); } $correct = 0; $review = array(); foreach ( $quiz as $i => $item ) { $given = isset( $answers[ $i ] ) ? (int) $answers[ $i ] : -1; if ( $given < 0 || $given > 2 ) { $given = -1; } $answer_index = isset( $item['a'] ) ? (int) $item['a'] : 0; if ( $answer_index < 0 || $answer_index > 2 || empty( $item['o'][ $answer_index ] ) ) { $answer_index = 0; } $ok = $given === $answer_index; if ( $ok ) { $correct++; } $review[] = array( 'correct' => $ok, 'answer' => $item['o'][ $answer_index ], 'explanation' => isset( $item['e'] ) ? $item['e'] : '' ); } $score = (int) round( 100 * $correct / count( $quiz ) ); $this->progress( $user, $lesson, 'started', $score ); wp_send_json_success( array( 'score' => $score, 'correct' => $correct, 'total' => count( $quiz ), 'review' => $review ) ); }
	private function progress( $user, $lesson, $status, $score = null ) { global $wpdb; $table = $wpdb->prefix . 'slc_progress'; $current = $wpdb->get_row( $wpdb->prepare( "SELECT * FROM {$table} WHERE user_id=%d AND lesson_id=%d", $user, $lesson ) ); $data = array( 'user_id' => $user, 'lesson_id' => $lesson, 'status' => $current && 'completed' === $current->status ? 'completed' : $status, 'score' => null === $score ? ( $current ? absint( $current->score ) : 0 ) : max( $current ? absint( $current->score ) : 0, absint( $score ) ), 'updated_at' => current_time( 'mysql', true ) ); $wpdb->replace( $table, $data, array( '%d', '%d', '%s', '%d', '%s' ) ); }
	public function track() { if ( ! is_singular( SLC_Content::LESSON ) ) { return; } $id = get_queried_object_id(); if ( is_user_logged_in() ) { $this->progress( get_current_user_id(), $id, 'started' ); } $cookie = 'slc_viewed_' . $id; if ( ! isset( $_COOKIE[ $cookie ] ) ) { update_post_meta( $id, '_slc_views', absint( get_post_meta( $id, '_slc_views', true ) ) + 1 ); setcookie( $cookie, '1', array( 'expires' => time() + 12 * HOUR_IN_SECONDS, 'path' => COOKIEPATH ? COOKIEPATH : '/', 'secure' => is_ssl(), 'httponly' => true, 'samesite' => 'Lax' ) ); } }
	public static function bookmarked( $lesson, $user = 0 ) { global $wpdb; $user = $user ? absint( $user ) : get_current_user_id(); return $user && (bool) $wpdb->get_var( $wpdb->prepare( "SELECT id FROM {$wpdb->prefix}slc_bookmarks WHERE user_id=%d AND lesson_id=%d", $user, absint( $lesson ) ) ); }
	public static function status( $lesson, $user = 0 ) { global $wpdb; $user = $user ? absint( $user ) : get_current_user_id(); return $user ? (string) $wpdb->get_var( $wpdb->prepare( "SELECT status FROM {$wpdb->prefix}slc_progress WHERE user_id=%d AND lesson_id=%d", $user, absint( $lesson ) ) ) : ''; }
	public static function actions( $lesson ) { $logged = is_user_logged_in(); $saved = $logged && self::bookmarked( $lesson ); $complete = $logged && 'completed' === self::status( $lesson ); ob_start(); ?><div class="slc-actions" data-slc-actions><?php if ( $logged ) : ?><button type="button" data-slc-action="bookmark" aria-pressed="<?php echo $saved ? 'true' : 'false'; ?>" class="<?php echo $saved ? 'is-active' : ''; ?>"><?php echo $saved ? 'Bookmarked' : 'Bookmark'; ?></button><button type="button" data-slc-action="complete" aria-pressed="<?php echo $complete ? 'true' : 'false'; ?>" class="<?php echo $complete ? 'is-active' : ''; ?>"><?php echo $complete ? 'Completed' : 'Mark as Complete'; ?></button><?php else : ?><a href="<?php echo esc_url( wp_login_url( get_permalink( $lesson ) ) ); ?>">Log in to track progress</a><?php endif; ?></div><?php return ob_get_clean(); }
	public static function quiz_form( $lesson ) { $quiz = get_post_meta( $lesson, '_slc_quiz', true ); if ( ! is_array( $quiz ) || ! $quiz ) { return ''; } ob_start(); ?><section class="slc-quiz"><h2>Knowledge Check</h2><form data-slc-quiz><?php foreach ( $quiz as $i => $item ) : ?><fieldset><legend><?php echo esc_html( ( $i + 1 ) . '. ' . $item['q'] ); ?></legend><?php foreach ( $item['o'] as $j => $option ) : ?><label><input type="radio" name="q<?php echo absint( $i ); ?>" value="<?php echo absint( $j ); ?>" required> <?php echo esc_html( $option ); ?></label><?php endforeach; ?></fieldset><?php endforeach; ?><?php if ( is_user_logged_in() ) : ?><button class="slc-button" type="submit">Check Answers</button><?php else : ?><a class="slc-button" href="<?php echo esc_url( wp_login_url( get_permalink( $lesson ) ) ); ?>">Log In to Take Check</a><?php endif; ?><div data-slc-quiz-result aria-live="polite"></div></form></section><?php return ob_get_clean(); }
	public function dashboard() { if ( ! is_user_logged_in() ) { return '<div class="slc-notice"><p>Log in to view your learning progress.</p><a class="slc-button" href="' . esc_url( wp_login_url( get_permalink() ) ) . '">Log In</a></div>'; } global $wpdb; $user = get_current_user_id(); $rows = $wpdb->get_results( $wpdb->prepare( "SELECT * FROM {$wpdb->prefix}slc_progress WHERE user_id=%d ORDER BY updated_at DESC LIMIT 200", $user ) ); $bookmarks = $wpdb->get_col( $wpdb->prepare( "SELECT lesson_id FROM {$wpdb->prefix}slc_bookmarks WHERE user_id=%d ORDER BY created_at DESC", $user ) ); $total = count( get_posts( array( 'post_type' => SLC_Content::LESSON, 'post_status' => 'publish', 'posts_per_page' => -1, 'fields' => 'ids', 'no_found_rows' => true ) ) ); $completed = count( array_filter( $rows, function( $r ) { return 'completed' === $r->status; } ) ); $percent = $total ? round( 100 * $completed / $total ) : 0; ob_start(); ?><main class="slc-shell"><header class="slc-page-head"><span>Private Learning Dashboard</span><h1>My Learning</h1><p><?php echo absint( $completed ); ?> of <?php echo absint( $total ); ?> lessons completed — <?php echo absint( $percent ); ?>%</p><progress max="100" value="<?php echo absint( $percent ); ?>"><?php echo absint( $percent ); ?>%</progress></header><div class="slc-two"><section class="slc-panel"><h2>Continue Learning</h2><?php echo $this->lesson_list( wp_list_pluck( $rows, 'lesson_id' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></section><section class="slc-panel"><h2>Bookmarked Lessons</h2><?php echo $this->lesson_list( $bookmarks ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped ?></section></div></main><?php return ob_get_clean(); }
	private function lesson_list( $ids ) { if ( ! $ids ) { return '<p>No lessons here yet.</p>'; } $out = '<ul class="slc-lesson-list">'; foreach ( array_slice( array_map( 'absint', $ids ), 0, 20 ) as $id ) { if ( SLC_Content::LESSON === get_post_type( $id ) ) { $out .= '<li><a href="' . esc_url( get_permalink( $id ) ) . '">' . esc_html( get_the_title( $id ) ) . '</a></li>'; } } return $out . '</ul>'; }
	public function append_level_progress( $content ) { $pages = (array) get_option( 'slc_page_map', array() ); if ( ! is_user_logged_in() || empty( $pages['progress'] ) || ! is_page( absint( $pages['progress'] ) ) || ! in_the_loop() || ! is_main_query() ) { return $content; } global $wpdb; $completed = $wpdb->get_col( $wpdb->prepare( "SELECT lesson_id FROM {$wpdb->prefix}slc_progress WHERE user_id=%d AND status='completed'", get_current_user_id() ) ); $out = '<section class="slc-shell"><div class="slc-panel"><h2>Progress by Level</h2><div class="slc-level-progress">'; foreach ( SLC_Content::levels() as $slug => $name ) { $ids = get_posts( array( 'post_type' => SLC_Content::LESSON, 'post_status' => 'publish', 'posts_per_page' => -1, 'fields' => 'ids', 'tax_query' => array( array( 'taxonomy' => SLC_Content::LEVEL, 'field' => 'slug', 'terms' => $slug ) ), 'no_found_rows' => true ) ); $done = count( array_intersect( array_map( 'absint', $ids ), array_map( 'absint', $completed ) ) ); $total = count( $ids ); $percent = $total ? round( 100 * $done / $total ) : 0; $out .= '<div><strong>' . esc_html( $name ) . '</strong><span>' . absint( $done ) . '/' . absint( $total ) . '</span><progress max="100" value="' . absint( $percent ) . '">' . absint( $percent ) . '%</progress></div>'; } return $content . $out . '</div></div></section>'; }
}
