#!/usr/bin/env python3
from pathlib import Path
p = Path(__file__).with_name('review80-cycle3-20260811.py')
s = p.read_text(encoding='utf-8')
start = s.index('clean_topics = [')
end = s.index('\nif len(clean_topics) != 69:', start)
clean_topics = [
'plugin/runtime/schema/release identity and repository-document parity',
'canonical package root/text-domain and deterministic release inputs',
'cross-file canonical-owner boundaries for Files 06/12/15/16/17/19/20/25/26',
'File00 public assertion contract only/no private storage coupling',
'single-free-tier plus donation-neutrality/no paid learning advantage',
'Sabri Green fallback and File20/File25 shell/design ownership',
'public vs protected catalog cache/query partition',
'private dashboard/noindex/no-store behavior',
'lesson DTO visibility/entitlement recheck',
'object/field/IDOR authorization',
'suspension currentness on protected actions',
'guardian/age gate on protected actions',
'Safe Mode mutation blocking',
'Safe Mode diagnostic availability',
'WordPress administrator identity separation',
'native File05 capability currentness',
'governance meta nonce/current-policy enforcement',
'private-note independent AES-256-GCM keyring',
'legacy private-note decrypt-only compatibility',
'private-note key rotation boundedness',
'private-note decrypt failure observability',
'REST permission callback ordering',
'durable REST idempotency ledger',
'idempotency payload-conflict protection',
'idempotency replay privacy minimization',
'assessment attempt allocation concurrency',
'assessment attempt-limit enforcement',
'assessment expiry durable transition',
'assessment submit optimistic concurrency',
'assignment submission persistence truth',
'assignment assessor/object scope',
'appeal current-policy enforcement',
'enrollment prerequisite/eligibility enforcement',
'progress optimistic concurrency and persistence truth',
'lesson component bounded queries',
'course completion bounded enumeration/write-before-event',
'bookmark DB-failure truth',
'reminder write-before-event ordering',
'staff assignment/removal current-policy checks',
'patient-case consent current-policy checks',
'patient-case publication consent and کامیاب کیس governance',
'correction proposal/review separation of duties',
'correction advisory lock/version-impact semantics',
'saved-search ownership and bounded queries',
'core privacy export pagination/completeness',
'core privacy erasure failure visibility/idempotency cleanup',
'Future18 privacy export pagination',
'Future18 privacy erasure lifecycle',
'Future18 mastery supervision scope',
'spaced-repetition scheduling authority',
'flashcard privacy/ownership',
'clinical simulation de-identification',
'repertory external-owner adapter boundary',
'practice immutable competency snapshot',
'mentorship lifecycle/scope',
'CPD independent verification',
'Socratic AI source/citation gate',
'knowledge-change batching/targeted re-study',
'outbox retry/dead-letter locking',
'background-job retry/dead-letter locking',
'reconciliation and safe degraded operation',
'system-check table/schema/queue truth',
'PHP 7.4 compatibility',
'PHP 8.3 compatibility',
'JavaScript DOM and syntax safety',
'XSS/escaping/sanitization plus prepared-SQL review',
'secret/symlink/archive-traversal and deterministic-package integrity',
'RTL/keyboard/reduced-motion/accessibility source hooks',
'performance/migration/rollback/staging-live truth separation'
]
if len(clean_topics) != 69:
    raise SystemExit(f'hotfix list must contain 69 topics, got {len(clean_topics)}')
replacement = 'clean_topics = ' + repr(clean_topics)
s = s[:start] + replacement + s[end:]
p.write_text(s, encoding='utf-8', newline='\n')
print('Review-80 cycle3 clean-lens list corrected to 69 distinct closure rounds.')
